### ISSUE TITLE
Skin Tones not supported in EmojiOne.EmojiOne.ShortnameToUnicode

### ISSUE THREAD

**Issue by ultimaustin** [lajjne/emojione#5]
It looks like the EmojiOne.EmojiOne.ShortnameToUnicode method doesn't support skin tones.

Passing "smiley" wrapped in colons to this method returns the unicode character for a smiley as expected.

However, passing the string "smiley" wrapped in quotes with ":skin-tone-6:" appended to it returns 😃:skin-tone-6: (i.e. Smiley unicode character + ":skin-tone-6")

Am I doing something wrong or are skin tones not supported in the current version?

N.B. Please forgive the weird syntax in this issue. When I try to write the strings as they are used, github is converting the colon syntax to emojis which makes it difficult to describe the issue. Hopefully, the above is clear.

**Comment by lajjne** [comment]
Yes, skin tones are supported. But not all emoji support skin tones. The 😃 is one of those that does not come in different skin tones. Also there are only 5 skin tones (1-5). For example :thumbsup_tone5: will render 👍🏿.

**Comment by ultimaustin** [comment]
Thanks for such a fast response. 

It would appear then that there are different short-name syntax for skin tones. The libraries that I have been using all express  :thumbsup_tone5: as : thumbsup :: skin-tone-tone6 :

Do you know if there are standards on these short names? Is guess I can work around this by replacing ":: skin-tone-tone{X} :" with "_tone{X-1}" before passing to EmojiOne.

Would you consider incorporating something similar to this package to support both syntax variants?
